services:
  spellbook:
    build:
      context: .
    image: kliszaj/spellbook:latest
    container_name: spellbook
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATA_DIR: /app/data
    ports:
      - "3000:3000"
    volumes:
      - /mnt/user/appdata/spellbook/data:/app/data
